api_id: '6667465' # This has to be an integer.
api_hash: 'BACdYvwjPp1LNXjlOV2nZStxrzZkbx3HfqxM4y-stGrrQbNUuqyHRrQjNSc0BFwiSCcl7X4AVUCZ5ZRTcStTIhtp4zg6Z9S_f4TgzAs835TsYFR_-3wULWQ8SSkIs5xrwKCI5HY3isYP2187tuGNWH1gXR6UDZ5HN3I_mE1qmp6JFtAS0HkptD_E3eNcXD4o9UYxUFxwxk7aaH205BMVdd7Xlg3oHDDtFrMKXSG8H5eQKMjqn3BG7j74P5eDRoPQMnm2rT1g1jy9kcUM3qpalBadROLqjZ5y9MjlZ5iasFhXIg9qhtjFnbNQi1amUiiN5XhErFW60ic_xAS1qTdRF7GdR-blRAA' # Long 32 characters hash identifier.
session_name: 'forwardgram' # Session name.

# The channel IDs that you'd like to forward messages from. (You can get a channel ID by forwarding any message from it to @userinfobot , and removing the -100 from the start )
input_channel_ids:
  - 1006935927 # Input Channel ID without quotes ''
  - ID2

# The output channel IDs that the messages will be forwarded to. (You can get a channel ID by forwarding any message from it to @userinfobot , and removing the -100 from the start )
output_channel_ids: 
  - 1515924882 # Output Channel ID without quotes ''
  - ID2
